# Base configs
baseurl: "https://grace-li-cam.github.io/album/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: 

# UI configs
title: "Photography by Qi Li"
subtitle: "眼界改变世界，行走改变命运！"
author: "Qi Li"
header:
 title: "Photography"
 subtitle: "by Qi Li"
footer:
 name: 
 bio: 
 github: 
web_design:
social_urls:

